---
- hosts: cloud_servers
  remote_user: deploy
  become: true
  vars_files:
    - secrets/shared.yml
    - secrets/production.yml

  roles:
    - role: geerlingguy.passenger
      passenger_server_name: besieged.alxs.fr
      passenger_app_root: /var/www/besieged_production/current/public
      passenger_app_env: production
      passenger_ruby: /usr/local/rbenv/shims/ruby

    - role: geerlingguy.postgresql
      postgresql_databases:
        - name: besieged_production
      postgresql_users:
        - name: besieged_production
          password: "{{ db_password }}"

    # This role modify the nginx vhost file
    - role: besieged
      app_name: besieged_production
      rails_env: production
      db_name: besieged_production
      ruby_path: /usr/local/rbenv/shims/ruby

    # This role modify the nginx vhost file
    - role: certbot
      cert_email: "{{ besieged_email }}"
      cert_domains:
        - besieged.alxs.fr
