- src: zzet.rbenv
  version: 3.4.7
- src: singleplatform-eng.users
  version: v1.2.6
- src: geerlingguy.passenger
  version: 1.2.0
- src: geerlingguy.postgresql
  version: 2.0.2
- src: haelle.oh_my_zsh
  version: v0.9
- src: haelle.certbot_ansible
  version: v1.2
