---
- name: Add certbot repository
  apt_repository:
    repo: ppa:certbot/certbot

- name: Install packages for certifs
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - software-properties-common
    - python-certbot-nginx
    - letsencrypt

- include_tasks: create_cert_nginx.yml
  with_items: "{{ cert_domains }}"
  loop_control:
    loop_var: cert_domain

- name: auto-renew certif
  shell: certbot renew --dry-run
  ignore_errors: yes
  become: true
